### ISSUE TITLE
test failing

### ISSUE THREAD

**Issue by tracycollins** [extrabacon/google-oauth-jwt#13]
Hi,

Just trying out this module, 3 of the tests fail.  I'm running node v0.12.2.  I think I've setup my env as needed with .pem file, requested scopes, etc.  

Any ideas where I should look to fix this?

thanks!

tracy

--------------------

$ npm test

> google-oauth-jwt@0.1.4 test /Volumes/RAID1/projects/google-oauth-jwt-master
> mocha -t 5000 -R spec

WARNING: running these tests require a per-user configuration!!
To specify your configuration, copy `jwt-settings.json.sample` to `jwt-settings.json`

Make sure that your service account is setup, has been granted access to the requested scopes, and that you have converted your key to PEM

  encodeJWT()
    ✓ should sign a token with a string-based key 
    ✓ should sign a token with a key obtained from a file 
    ✓ should fail when options are missing or invalid 
    1) should fail when signing with an invalid key

  authenticate()
    ✓ should return a valid token for a legitimate request (237ms)
    ✓ should fail for an invalid request (148ms)

  TokenCache
    get()
      ✓ should request a token on first call 
      ✓ should reuse a token on subsequent calls (504ms)
      ✓ should issue only one request on concurrent calls 
      ✓ should discard an expired token and request another one (512ms)
    clear()
      ✓ should remove previously requested tokens (174ms)

  requestWithJWT
    ✓ should return a request function with helper methods 
    ✓ should work normally, without jwt settings (177ms)
    2) should request a token automatically
    3) should use a global token cache

  12 passing (2s)
  3 failing

  1) encodeJWT() should fail when signing with an invalid key:
     Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
      at Error (native)
      at Sign.sign (crypto.js:327:26)
      at /Volumes/RAID1/projects/google-oauth-jwt-master/lib/auth.js:112:75
      at obtainKey (/Volumes/RAID1/projects/google-oauth-jwt-master/lib/auth.js:127:11)
      at Object.exports.encodeJWT (/Volumes/RAID1/projects/google-oauth-jwt-master/lib/auth.js:108:2)
      at Context.<anonymous> (/Volumes/RAID1/projects/google-oauth-jwt-master/test/test-google-oauth-jwt.js:63:16)
      at Test.Runnable.run (/Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/mocha/lib/runnable.js:233:15)
      at Runner.runTest (/Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/mocha/lib/runner.js:387:10)
      at /Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/mocha/lib/runner.js:470:12
      at next (/Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/mocha/lib/runner.js:312:14)
      at /Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/mocha/lib/runner.js:322:7
      at next (/Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/mocha/lib/runner.js:257:23)
      at Immediate._onImmediate (/Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/mocha/lib/runner.js:289:5)
      at processImmediate [as _immediateCallback] (timers.js:358:17)

  2) requestWithJWT should request a token automatically:
     Uncaught TypeError: undefined is not a function
      at request.(anonymous function) (/Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/request/index.js:64:16)
      at /Volumes/RAID1/projects/google-oauth-jwt-master/lib/request-jwt.js:45:6
      at /Volumes/RAID1/projects/google-oauth-jwt-master/lib/token-cache.js:61:4
      at Array.forEach (native)
      at fireCallbacks (/Volumes/RAID1/projects/google-oauth-jwt-master/lib/token-cache.js:60:25)
      at /Volumes/RAID1/projects/google-oauth-jwt-master/lib/token-cache.js:82:12
      at Request._callback (/Volumes/RAID1/projects/google-oauth-jwt-master/lib/auth.js:56:11)
      at Request.self.callback (/Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/request/request.js:360:22)
      at Request.emit (events.js:110:17)
      at Request.<anonymous> (/Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/request/request.js:1202:14)
      at Request.emit (events.js:129:20)
      at IncomingMessage.<anonymous> (/Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/request/request.js:1150:12)
      at IncomingMessage.emit (events.js:129:20)
      at _stream_readable.js:908:16
      at process._tickCallback (node.js:355:11)

  3) requestWithJWT should use a global token cache:

      Uncaught AssertionError: expected 404 to equal 200
      + expected - actual

      +200
      -404
      
      at Request._callback (/Volumes/RAID1/projects/google-oauth-jwt-master/test/test-google-oauth-jwt.js:287:31)
      at Request.self.callback (/Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/request/request.js:360:22)
      at Request.emit (events.js:110:17)
      at Request.<anonymous> (/Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/request/request.js:1202:14)
      at Request.emit (events.js:129:20)
      at IncomingMessage.<anonymous> (/Volumes/RAID1/projects/google-oauth-jwt-master/node_modules/request/request.js:1150:12)
      at IncomingMessage.emit (events.js:129:20)
      at _stream_readable.js:908:16
      at process._tickCallback (node.js:355:11)

npm ERR! Test failed.  See above for more details.

**Comment by extrabacon** [comment]
Fixed in 0.1.5.
